version: '3.8'

services:
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image:
    depends_on:
      - db
    ports:
      - '8080:80'
    env_file:
      - fileName

volumes:
  progresDB:
